server.port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/soa_app_db
#    url: jdbc:postgresql://postgres:5432/soa_app_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: UUID
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
server:
  servlet:
    context-path: /api/shop

security:
  jwt:
    secret-key: verysecretkeyohsosecretdamnhowlongisthispleasedontusethisinproduction
    token-duration: 1D
